export const GET_API_ENDPOINTS_REQUEST = 'GET_API_ENDPOINTS_REQUEST';
export const GET_API_ENDPOINTS_SUCCESS = 'GET_API_ENDPOINTS_SUCCESS';
export const GET_API_ENDPOINTS_FAIL = 'GET_API_ENDPOINTS_FAIL';

export const ADD_API_ENDPOINT_REQUEST = 'ADD_API_ENDPOINT_REQUEST';
export const ADD_API_ENDPOINT_SUCCESS = 'ADD_API_ENDPOINT_SUCCESS';
export const ADD_API_ENDPOINT_FAIL = 'ADD_API_ENDPOINT_FAIL';

export const EDIT_API_ENDPOINT_REQUEST = 'EDIT_API_ENDPOINT_REQUEST';
export const EDIT_API_ENDPOINT_SUCCESS = 'EDIT_API_ENDPOINT_SUCCESS';
export const EDIT_API_ENDPOINT_FAIL = 'EDIT_API_ENDPOINT_FAIL';

export const DELETE_API_ENDPOINT_REQUEST = 'DELETE_API_ENDPOINT_REQUEST';
export const DELETE_API_ENDPOINT_SUCCESS = 'DELETE_API_ENDPOINT_SUCCESS';
export const DELETE_API_ENDPOINT_FAIL = 'DELETE_API_ENDPOINT_FAIL';