export const USER_GET_PROFILE_REQUEST = 'USER_GET_PROFILE_REQUEST'
export const USER_GET_PROFILE_SUCCESS = 'USER_GET_PROFILE_SUCCESS'
export const USER_GET_PROFILE_FAIL = 'USER_GET_PROFILE_FAIL'

export const USER_UPDATE_PROFILE_REQUEST = 'USER_UPDATE_PROFILE_REQUEST'
export const USER_UPDATE_PROFILE_SUCCESS = 'USER_UPDATE_PROFILE_SUCCESS'
export const USER_UPDATE_PROFILE_FAIL = 'USER_UPDATE_PROFILE_FAIL'
export const USER_UPDATE_PROFILE_RESET = 'USER_UPDATE_PROFILE_RESET'

export const USER_UPLOAD_PROFILE_REQUEST = 'USER_UPLOAD_PROFILE_REQUEST'
export const USER_UPLOAD_PROFILE_SUCCESS = 'USER_UPLOAD_PROFILE_SUCCESS'
export const USER_UPLOAD_PROFILE_FAIL = 'USER_UPLOAD_PROFILE_FAIL'
export const USER_UPLOAD_PROFILE_RESET = 'USER_UPLOAD_PROFILE_RESET'